// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianReplyStatsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianReplyStatsService is a mock of VeridianReplyStatsService interface.
type MockVeridianReplyStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianReplyStatsServiceMockRecorder
}

// MockVeridianReplyStatsServiceMockRecorder is the mock recorder for MockVeridianReplyStatsService.
type MockVeridianReplyStatsServiceMockRecorder struct {
	mock *MockVeridianReplyStatsService
}

// NewMockVeridianReplyStatsService creates a new mock instance.
func NewMockVeridianReplyStatsService(ctrl *gomock.Controller) *MockVeridianReplyStatsService {
	mock := &MockVeridianReplyStatsService{ctrl: ctrl}
	mock.recorder = &MockVeridianReplyStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianReplyStatsService) EXPECT() *MockVeridianReplyStatsServiceMockRecorder {
	return m.recorder
}

// GetReplyStats mocks base method.
func (m *MockVeridianReplyStatsService) GetReplyStats(arg0 context.Context, arg1 *domain.VeridianReplyStatsRequest) (*domain.VeridianReplyStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplyStats", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianReplyStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplyStats indicates an expected call of GetReplyStats.
func (mr *MockVeridianReplyStatsServiceMockRecorder) GetReplyStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplyStats", reflect.TypeOf((*MockVeridianReplyStatsService)(nil).GetReplyStats), arg0, arg1)
}
