// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianContactProviderBreakdownRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianContactProviderBreakdownRepository is a mock of VeridianContactProviderBreakdownRepository interface.
type MockVeridianContactProviderBreakdownRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianContactProviderBreakdownRepositoryMockRecorder
}

// MockVeridianContactProviderBreakdownRepositoryMockRecorder is the mock recorder for MockVeridianContactProviderBreakdownRepository.
type MockVeridianContactProviderBreakdownRepositoryMockRecorder struct {
	mock *MockVeridianContactProviderBreakdownRepository
}

// NewMockVeridianContactProviderBreakdownRepository creates a new mock instance.
func NewMockVeridianContactProviderBreakdownRepository(ctrl *gomock.Controller) *MockVeridianContactProviderBreakdownRepository {
	mock := &MockVeridianContactProviderBreakdownRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianContactProviderBreakdownRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianContactProviderBreakdownRepository) EXPECT() *MockVeridianContactProviderBreakdownRepositoryMockRecorder {
	return m.recorder
}

// GetProviderClassCounts mocks base method.
func (m *MockVeridianContactProviderBreakdownRepository) GetProviderClassCounts(arg0 context.Context, arg1, arg2 string) ([]domain.VeridianContactProviderCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderClassCounts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.VeridianContactProviderCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderClassCounts indicates an expected call of GetProviderClassCounts.
func (mr *MockVeridianContactProviderBreakdownRepositoryMockRecorder) GetProviderClassCounts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderClassCounts", reflect.TypeOf((*MockVeridianContactProviderBreakdownRepository)(nil).GetProviderClassCounts), arg0, arg1, arg2)
}
