// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianReputationStatusService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianReputationStatusService is a mock of VeridianReputationStatusService interface.
type MockVeridianReputationStatusService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianReputationStatusServiceMockRecorder
}

// MockVeridianReputationStatusServiceMockRecorder is the mock recorder for MockVeridianReputationStatusService.
type MockVeridianReputationStatusServiceMockRecorder struct {
	mock *MockVeridianReputationStatusService
}

// NewMockVeridianReputationStatusService creates a new mock instance.
func NewMockVeridianReputationStatusService(ctrl *gomock.Controller) *MockVeridianReputationStatusService {
	mock := &MockVeridianReputationStatusService{ctrl: ctrl}
	mock.recorder = &MockVeridianReputationStatusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianReputationStatusService) EXPECT() *MockVeridianReputationStatusServiceMockRecorder {
	return m.recorder
}

// GetReputationStatus mocks base method.
func (m *MockVeridianReputationStatusService) GetReputationStatus(arg0 context.Context, arg1 *domain.VeridianReputationStatusRequest) (*domain.VeridianReputationStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReputationStatus", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianReputationStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReputationStatus indicates an expected call of GetReputationStatus.
func (mr *MockVeridianReputationStatusServiceMockRecorder) GetReputationStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReputationStatus", reflect.TypeOf((*MockVeridianReputationStatusService)(nil).GetReputationStatus), arg0, arg1)
}
