// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianContactProviderBreakdownService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianContactProviderBreakdownService is a mock of VeridianContactProviderBreakdownService interface.
type MockVeridianContactProviderBreakdownService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianContactProviderBreakdownServiceMockRecorder
}

// MockVeridianContactProviderBreakdownServiceMockRecorder is the mock recorder for MockVeridianContactProviderBreakdownService.
type MockVeridianContactProviderBreakdownServiceMockRecorder struct {
	mock *MockVeridianContactProviderBreakdownService
}

// NewMockVeridianContactProviderBreakdownService creates a new mock instance.
func NewMockVeridianContactProviderBreakdownService(ctrl *gomock.Controller) *MockVeridianContactProviderBreakdownService {
	mock := &MockVeridianContactProviderBreakdownService{ctrl: ctrl}
	mock.recorder = &MockVeridianContactProviderBreakdownServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianContactProviderBreakdownService) EXPECT() *MockVeridianContactProviderBreakdownServiceMockRecorder {
	return m.recorder
}

// GetProviderBreakdown mocks base method.
func (m *MockVeridianContactProviderBreakdownService) GetProviderBreakdown(arg0 context.Context, arg1 *domain.VeridianProviderBreakdownRequest) (*domain.VeridianProviderBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderBreakdown", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianProviderBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderBreakdown indicates an expected call of GetProviderBreakdown.
func (mr *MockVeridianContactProviderBreakdownServiceMockRecorder) GetProviderBreakdown(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderBreakdown", reflect.TypeOf((*MockVeridianContactProviderBreakdownService)(nil).GetProviderBreakdown), arg0, arg1)
}
