// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianIMAPConsumer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianIMAPConsumer is a mock of VeridianIMAPConsumer interface.
type MockVeridianIMAPConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianIMAPConsumerMockRecorder
}

// MockVeridianIMAPConsumerMockRecorder is the mock recorder for MockVeridianIMAPConsumer.
type MockVeridianIMAPConsumerMockRecorder struct {
	mock *MockVeridianIMAPConsumer
}

// NewMockVeridianIMAPConsumer creates a new mock instance.
func NewMockVeridianIMAPConsumer(ctrl *gomock.Controller) *MockVeridianIMAPConsumer {
	mock := &MockVeridianIMAPConsumer{ctrl: ctrl}
	mock.recorder = &MockVeridianIMAPConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianIMAPConsumer) EXPECT() *MockVeridianIMAPConsumerMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockVeridianIMAPConsumer) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockVeridianIMAPConsumerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockVeridianIMAPConsumer)(nil).Name))
}

// OnNewMessage mocks base method.
func (m *MockVeridianIMAPConsumer) OnNewMessage(arg0 *domain.VeridianIMAPMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnNewMessage", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnNewMessage indicates an expected call of OnNewMessage.
func (mr *MockVeridianIMAPConsumerMockRecorder) OnNewMessage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNewMessage", reflect.TypeOf((*MockVeridianIMAPConsumer)(nil).OnNewMessage), arg0)
}
