// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianProspectionStatsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianProspectionStatsRepository is a mock of VeridianProspectionStatsRepository interface.
type MockVeridianProspectionStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianProspectionStatsRepositoryMockRecorder
}

// MockVeridianProspectionStatsRepositoryMockRecorder is the mock recorder for MockVeridianProspectionStatsRepository.
type MockVeridianProspectionStatsRepositoryMockRecorder struct {
	mock *MockVeridianProspectionStatsRepository
}

// NewMockVeridianProspectionStatsRepository creates a new mock instance.
func NewMockVeridianProspectionStatsRepository(ctrl *gomock.Controller) *MockVeridianProspectionStatsRepository {
	mock := &MockVeridianProspectionStatsRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianProspectionStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianProspectionStatsRepository) EXPECT() *MockVeridianProspectionStatsRepositoryMockRecorder {
	return m.recorder
}

// GetProspectionRaw mocks base method.
func (m *MockVeridianProspectionStatsRepository) GetProspectionRaw(arg0 context.Context, arg1 string, arg2, arg3 time.Time) (*domain.VeridianProspectionRaw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProspectionRaw", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.VeridianProspectionRaw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProspectionRaw indicates an expected call of GetProspectionRaw.
func (mr *MockVeridianProspectionStatsRepositoryMockRecorder) GetProspectionRaw(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProspectionRaw", reflect.TypeOf((*MockVeridianProspectionStatsRepository)(nil).GetProspectionRaw), arg0, arg1, arg2, arg3)
}
