// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianProspectionStatsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianProspectionStatsService is a mock of VeridianProspectionStatsService interface.
type MockVeridianProspectionStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianProspectionStatsServiceMockRecorder
}

// MockVeridianProspectionStatsServiceMockRecorder is the mock recorder for MockVeridianProspectionStatsService.
type MockVeridianProspectionStatsServiceMockRecorder struct {
	mock *MockVeridianProspectionStatsService
}

// NewMockVeridianProspectionStatsService creates a new mock instance.
func NewMockVeridianProspectionStatsService(ctrl *gomock.Controller) *MockVeridianProspectionStatsService {
	mock := &MockVeridianProspectionStatsService{ctrl: ctrl}
	mock.recorder = &MockVeridianProspectionStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianProspectionStatsService) EXPECT() *MockVeridianProspectionStatsServiceMockRecorder {
	return m.recorder
}

// GetProspectionStats mocks base method.
func (m *MockVeridianProspectionStatsService) GetProspectionStats(arg0 context.Context, arg1 *domain.VeridianProspectionStatsRequest) (*domain.VeridianProspectionStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProspectionStats", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianProspectionStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProspectionStats indicates an expected call of GetProspectionStats.
func (mr *MockVeridianProspectionStatsServiceMockRecorder) GetProspectionStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProspectionStats", reflect.TypeOf((*MockVeridianProspectionStatsService)(nil).GetProspectionStats), arg0, arg1)
}
