// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianEngagementByClassService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianEngagementByClassService is a mock of VeridianEngagementByClassService interface.
type MockVeridianEngagementByClassService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianEngagementByClassServiceMockRecorder
}

// MockVeridianEngagementByClassServiceMockRecorder is the mock recorder for MockVeridianEngagementByClassService.
type MockVeridianEngagementByClassServiceMockRecorder struct {
	mock *MockVeridianEngagementByClassService
}

// NewMockVeridianEngagementByClassService creates a new mock instance.
func NewMockVeridianEngagementByClassService(ctrl *gomock.Controller) *MockVeridianEngagementByClassService {
	mock := &MockVeridianEngagementByClassService{ctrl: ctrl}
	mock.recorder = &MockVeridianEngagementByClassServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianEngagementByClassService) EXPECT() *MockVeridianEngagementByClassServiceMockRecorder {
	return m.recorder
}

// GetEngagementByClass mocks base method.
func (m *MockVeridianEngagementByClassService) GetEngagementByClass(arg0 context.Context, arg1 *domain.VeridianEngagementByClassRequest) (*domain.VeridianEngagementByClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEngagementByClass", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianEngagementByClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEngagementByClass indicates an expected call of GetEngagementByClass.
func (mr *MockVeridianEngagementByClassServiceMockRecorder) GetEngagementByClass(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEngagementByClass", reflect.TypeOf((*MockVeridianEngagementByClassService)(nil).GetEngagementByClass), arg0, arg1)
}
