// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebhookEmitter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebhookEmitter is a mock of WebhookEmitter interface.
type MockWebhookEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookEmitterMockRecorder
}

// MockWebhookEmitterMockRecorder is the mock recorder for MockWebhookEmitter.
type MockWebhookEmitterMockRecorder struct {
	mock *MockWebhookEmitter
}

// NewMockWebhookEmitter creates a new mock instance.
func NewMockWebhookEmitter(ctrl *gomock.Controller) *MockWebhookEmitter {
	mock := &MockWebhookEmitter{ctrl: ctrl}
	mock.recorder = &MockWebhookEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookEmitter) EXPECT() *MockWebhookEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockWebhookEmitter) Emit(arg0 context.Context, arg1 domain.VeridianEvent, arg2 string, arg3 map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", arg0, arg1, arg2, arg3)
}

// Emit indicates an expected call of Emit.
func (mr *MockWebhookEmitterMockRecorder) Emit(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockWebhookEmitter)(nil).Emit), arg0, arg1, arg2, arg3)
}
