// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianPlanRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianPlanRepository is a mock of VeridianPlanRepository interface.
type MockVeridianPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianPlanRepositoryMockRecorder
}

// MockVeridianPlanRepositoryMockRecorder is the mock recorder for MockVeridianPlanRepository.
type MockVeridianPlanRepositoryMockRecorder struct {
	mock *MockVeridianPlanRepository
}

// NewMockVeridianPlanRepository creates a new mock instance.
func NewMockVeridianPlanRepository(ctrl *gomock.Controller) *MockVeridianPlanRepository {
	mock := &MockVeridianPlanRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianPlanRepository) EXPECT() *MockVeridianPlanRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVeridianPlanRepository) Get(arg0 context.Context, arg1 string) (*domain.VeridianPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVeridianPlanRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVeridianPlanRepository)(nil).Get), arg0, arg1)
}

// HardDelete mocks base method.
func (m *MockVeridianPlanRepository) HardDelete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockVeridianPlanRepositoryMockRecorder) HardDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockVeridianPlanRepository)(nil).HardDelete), arg0, arg1)
}

// IncrementEmailsSent mocks base method.
func (m *MockVeridianPlanRepository) IncrementEmailsSent(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementEmailsSent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementEmailsSent indicates an expected call of IncrementEmailsSent.
func (mr *MockVeridianPlanRepositoryMockRecorder) IncrementEmailsSent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementEmailsSent", reflect.TypeOf((*MockVeridianPlanRepository)(nil).IncrementEmailsSent), arg0, arg1, arg2)
}

// ListByPrefix mocks base method.
func (m *MockVeridianPlanRepository) ListByPrefix(arg0 context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPrefix", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPrefix indicates an expected call of ListByPrefix.
func (mr *MockVeridianPlanRepositoryMockRecorder) ListByPrefix(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPrefix", reflect.TypeOf((*MockVeridianPlanRepository)(nil).ListByPrefix), arg0, arg1)
}

// ResetMonthlyCounters mocks base method.
func (m *MockVeridianPlanRepository) ResetMonthlyCounters(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetMonthlyCounters", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetMonthlyCounters indicates an expected call of ResetMonthlyCounters.
func (mr *MockVeridianPlanRepositoryMockRecorder) ResetMonthlyCounters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetMonthlyCounters", reflect.TypeOf((*MockVeridianPlanRepository)(nil).ResetMonthlyCounters), arg0)
}

// Resume mocks base method.
func (m *MockVeridianPlanRepository) Resume(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockVeridianPlanRepositoryMockRecorder) Resume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockVeridianPlanRepository)(nil).Resume), arg0, arg1)
}

// SoftDelete mocks base method.
func (m *MockVeridianPlanRepository) SoftDelete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockVeridianPlanRepositoryMockRecorder) SoftDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockVeridianPlanRepository)(nil).SoftDelete), arg0, arg1)
}

// Suspend mocks base method.
func (m *MockVeridianPlanRepository) Suspend(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockVeridianPlanRepositoryMockRecorder) Suspend(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockVeridianPlanRepository)(nil).Suspend), arg0, arg1, arg2)
}

// UpdatePlan mocks base method.
func (m *MockVeridianPlanRepository) UpdatePlan(arg0 context.Context, arg1, arg2 string, arg3 int64, arg4 domain.PlanSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlan indicates an expected call of UpdatePlan.
func (mr *MockVeridianPlanRepositoryMockRecorder) UpdatePlan(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockVeridianPlanRepository)(nil).UpdatePlan), arg0, arg1, arg2, arg3, arg4)
}

// Upsert mocks base method.
func (m *MockVeridianPlanRepository) Upsert(arg0 context.Context, arg1 *domain.VeridianPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockVeridianPlanRepositoryMockRecorder) Upsert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockVeridianPlanRepository)(nil).Upsert), arg0, arg1)
}
