// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianIMAPUIDSeenRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVeridianIMAPUIDSeenRepository is a mock of VeridianIMAPUIDSeenRepository interface.
type MockVeridianIMAPUIDSeenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianIMAPUIDSeenRepositoryMockRecorder
}

// MockVeridianIMAPUIDSeenRepositoryMockRecorder is the mock recorder for MockVeridianIMAPUIDSeenRepository.
type MockVeridianIMAPUIDSeenRepositoryMockRecorder struct {
	mock *MockVeridianIMAPUIDSeenRepository
}

// NewMockVeridianIMAPUIDSeenRepository creates a new mock instance.
func NewMockVeridianIMAPUIDSeenRepository(ctrl *gomock.Controller) *MockVeridianIMAPUIDSeenRepository {
	mock := &MockVeridianIMAPUIDSeenRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianIMAPUIDSeenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianIMAPUIDSeenRepository) EXPECT() *MockVeridianIMAPUIDSeenRepositoryMockRecorder {
	return m.recorder
}

// FilterUnseen mocks base method.
func (m *MockVeridianIMAPUIDSeenRepository) FilterUnseen(arg0 context.Context, arg1, arg2, arg3 string, arg4 uint32, arg5 []uint32) ([]uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUnseen", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterUnseen indicates an expected call of FilterUnseen.
func (mr *MockVeridianIMAPUIDSeenRepositoryMockRecorder) FilterUnseen(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUnseen", reflect.TypeOf((*MockVeridianIMAPUIDSeenRepository)(nil).FilterUnseen), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MarkSeen mocks base method.
func (m *MockVeridianIMAPUIDSeenRepository) MarkSeen(arg0 context.Context, arg1, arg2, arg3 string, arg4 uint32, arg5 []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSeen", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSeen indicates an expected call of MarkSeen.
func (mr *MockVeridianIMAPUIDSeenRepositoryMockRecorder) MarkSeen(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSeen", reflect.TypeOf((*MockVeridianIMAPUIDSeenRepository)(nil).MarkSeen), arg0, arg1, arg2, arg3, arg4, arg5)
}
