// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: AgentInstallTokenRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAgentInstallTokenRepository is a mock of AgentInstallTokenRepository interface.
type MockAgentInstallTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInstallTokenRepositoryMockRecorder
}

// MockAgentInstallTokenRepositoryMockRecorder is the mock recorder for MockAgentInstallTokenRepository.
type MockAgentInstallTokenRepositoryMockRecorder struct {
	mock *MockAgentInstallTokenRepository
}

// NewMockAgentInstallTokenRepository creates a new mock instance.
func NewMockAgentInstallTokenRepository(ctrl *gomock.Controller) *MockAgentInstallTokenRepository {
	mock := &MockAgentInstallTokenRepository{ctrl: ctrl}
	mock.recorder = &MockAgentInstallTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInstallTokenRepository) EXPECT() *MockAgentInstallTokenRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAgentInstallTokenRepository) Insert(arg0 context.Context, arg1 *domain.AgentInstallTokenRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAgentInstallTokenRepositoryMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAgentInstallTokenRepository)(nil).Insert), arg0, arg1)
}

// ClaimByHash mocks base method.
func (m *MockAgentInstallTokenRepository) ClaimByHash(arg0 context.Context, arg1 string, arg2 time.Time) (*domain.AgentInstallTokenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimByHash", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.AgentInstallTokenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimByHash indicates an expected call of ClaimByHash.
func (mr *MockAgentInstallTokenRepositoryMockRecorder) ClaimByHash(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimByHash", reflect.TypeOf((*MockAgentInstallTokenRepository)(nil).ClaimByHash), arg0, arg1, arg2)
}
