// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianIdempotencyRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianIdempotencyRepository is a mock of VeridianIdempotencyRepository interface.
type MockVeridianIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianIdempotencyRepositoryMockRecorder
}

// MockVeridianIdempotencyRepositoryMockRecorder is the mock recorder for MockVeridianIdempotencyRepository.
type MockVeridianIdempotencyRepositoryMockRecorder struct {
	mock *MockVeridianIdempotencyRepository
}

// NewMockVeridianIdempotencyRepository creates a new mock instance.
func NewMockVeridianIdempotencyRepository(ctrl *gomock.Controller) *MockVeridianIdempotencyRepository {
	mock := &MockVeridianIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianIdempotencyRepository) EXPECT() *MockVeridianIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// DeleteExpired mocks base method.
func (m *MockVeridianIdempotencyRepository) DeleteExpired(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockVeridianIdempotencyRepositoryMockRecorder) DeleteExpired(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockVeridianIdempotencyRepository)(nil).DeleteExpired), arg0)
}

// Get mocks base method.
func (m *MockVeridianIdempotencyRepository) Get(arg0 context.Context, arg1 string) (*domain.VeridianIdempotencyEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*domain.VeridianIdempotencyEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVeridianIdempotencyRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVeridianIdempotencyRepository)(nil).Get), arg0, arg1)
}

// Save mocks base method.
func (m *MockVeridianIdempotencyRepository) Save(arg0 context.Context, arg1 *domain.VeridianIdempotencyEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockVeridianIdempotencyRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockVeridianIdempotencyRepository)(nil).Save), arg0, arg1)
}
