// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianEngagementByClassRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianEngagementByClassRepository is a mock of VeridianEngagementByClassRepository interface.
type MockVeridianEngagementByClassRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianEngagementByClassRepositoryMockRecorder
}

// MockVeridianEngagementByClassRepositoryMockRecorder is the mock recorder for MockVeridianEngagementByClassRepository.
type MockVeridianEngagementByClassRepositoryMockRecorder struct {
	mock *MockVeridianEngagementByClassRepository
}

// NewMockVeridianEngagementByClassRepository creates a new mock instance.
func NewMockVeridianEngagementByClassRepository(ctrl *gomock.Controller) *MockVeridianEngagementByClassRepository {
	mock := &MockVeridianEngagementByClassRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianEngagementByClassRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianEngagementByClassRepository) EXPECT() *MockVeridianEngagementByClassRepositoryMockRecorder {
	return m.recorder
}

// GetEngagementByDomain mocks base method.
func (m *MockVeridianEngagementByClassRepository) GetEngagementByDomain(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]domain.VeridianDomainEngagementRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEngagementByDomain", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]domain.VeridianDomainEngagementRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEngagementByDomain indicates an expected call of GetEngagementByDomain.
func (mr *MockVeridianEngagementByClassRepositoryMockRecorder) GetEngagementByDomain(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEngagementByDomain", reflect.TypeOf((*MockVeridianEngagementByClassRepository)(nil).GetEngagementByDomain), arg0, arg1, arg2, arg3)
}
