// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianDeliverabilityScoreService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	deliverability "github.com/Notifuse/notifuse/pkg/veridian_deliverability"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianDeliverabilityScoreService is a mock of VeridianDeliverabilityScoreService interface.
type MockVeridianDeliverabilityScoreService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianDeliverabilityScoreServiceMockRecorder
}

// MockVeridianDeliverabilityScoreServiceMockRecorder is the mock recorder for MockVeridianDeliverabilityScoreService.
type MockVeridianDeliverabilityScoreServiceMockRecorder struct {
	mock *MockVeridianDeliverabilityScoreService
}

// NewMockVeridianDeliverabilityScoreService creates a new mock instance.
func NewMockVeridianDeliverabilityScoreService(ctrl *gomock.Controller) *MockVeridianDeliverabilityScoreService {
	mock := &MockVeridianDeliverabilityScoreService{ctrl: ctrl}
	mock.recorder = &MockVeridianDeliverabilityScoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianDeliverabilityScoreService) EXPECT() *MockVeridianDeliverabilityScoreServiceMockRecorder {
	return m.recorder
}

// Score mocks base method.
func (m *MockVeridianDeliverabilityScoreService) Score(arg0 context.Context, arg1 *domain.VeridianDeliverabilityScoreRequest) (*deliverability.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Score", arg0, arg1)
	ret0, _ := ret[0].(*deliverability.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Score indicates an expected call of Score.
func (mr *MockVeridianDeliverabilityScoreServiceMockRecorder) Score(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Score", reflect.TypeOf((*MockVeridianDeliverabilityScoreService)(nil).Score), arg0, arg1)
}
