// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianFrozenMemberRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianFrozenMemberRepository is a mock of VeridianFrozenMemberRepository interface.
type MockVeridianFrozenMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianFrozenMemberRepositoryMockRecorder
}

// MockVeridianFrozenMemberRepositoryMockRecorder is the mock recorder for MockVeridianFrozenMemberRepository.
type MockVeridianFrozenMemberRepositoryMockRecorder struct {
	mock *MockVeridianFrozenMemberRepository
}

// NewMockVeridianFrozenMemberRepository creates a new mock instance.
func NewMockVeridianFrozenMemberRepository(ctrl *gomock.Controller) *MockVeridianFrozenMemberRepository {
	mock := &MockVeridianFrozenMemberRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianFrozenMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianFrozenMemberRepository) EXPECT() *MockVeridianFrozenMemberRepositoryMockRecorder {
	return m.recorder
}

// Freeze mocks base method.
func (m *MockVeridianFrozenMemberRepository) Freeze(arg0 context.Context, arg1, arg2 string, arg3 domain.FreezeReason) (*domain.VeridianFrozenMember, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Freeze", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.VeridianFrozenMember)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Freeze indicates an expected call of Freeze.
func (mr *MockVeridianFrozenMemberRepositoryMockRecorder) Freeze(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freeze", reflect.TypeOf((*MockVeridianFrozenMemberRepository)(nil).Freeze), arg0, arg1, arg2, arg3)
}

// Unfreeze mocks base method.
func (m *MockVeridianFrozenMemberRepository) Unfreeze(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfreeze", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unfreeze indicates an expected call of Unfreeze.
func (mr *MockVeridianFrozenMemberRepositoryMockRecorder) Unfreeze(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfreeze", reflect.TypeOf((*MockVeridianFrozenMemberRepository)(nil).Unfreeze), arg0, arg1, arg2)
}

// IsFrozen mocks base method.
func (m *MockVeridianFrozenMemberRepository) IsFrozen(arg0 context.Context, arg1, arg2 string) (bool, domain.FreezeReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFrozen", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(domain.FreezeReason)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsFrozen indicates an expected call of IsFrozen.
func (mr *MockVeridianFrozenMemberRepositoryMockRecorder) IsFrozen(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFrozen", reflect.TypeOf((*MockVeridianFrozenMemberRepository)(nil).IsFrozen), arg0, arg1, arg2)
}
