// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianContactReplyRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianContactReplyRepository is a mock of VeridianContactReplyRepository interface.
type MockVeridianContactReplyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianContactReplyRepositoryMockRecorder
}

// MockVeridianContactReplyRepositoryMockRecorder is the mock recorder for MockVeridianContactReplyRepository.
type MockVeridianContactReplyRepositoryMockRecorder struct {
	mock *MockVeridianContactReplyRepository
}

// NewMockVeridianContactReplyRepository creates a new mock instance.
func NewMockVeridianContactReplyRepository(ctrl *gomock.Controller) *MockVeridianContactReplyRepository {
	mock := &MockVeridianContactReplyRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianContactReplyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianContactReplyRepository) EXPECT() *MockVeridianContactReplyRepositoryMockRecorder {
	return m.recorder
}

// HasReplied mocks base method.
func (m *MockVeridianContactReplyRepository) HasReplied(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasReplied", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasReplied indicates an expected call of HasReplied.
func (mr *MockVeridianContactReplyRepositoryMockRecorder) HasReplied(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasReplied", reflect.TypeOf((*MockVeridianContactReplyRepository)(nil).HasReplied), arg0, arg1, arg2)
}

// MarkReplied mocks base method.
func (m *MockVeridianContactReplyRepository) MarkReplied(arg0 context.Context, arg1 string, arg2 *domain.VeridianContactReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReplied", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkReplied indicates an expected call of MarkReplied.
func (mr *MockVeridianContactReplyRepositoryMockRecorder) MarkReplied(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReplied", reflect.TypeOf((*MockVeridianContactReplyRepository)(nil).MarkReplied), arg0, arg1, arg2)
}
