// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianService is a mock of VeridianService interface.
type MockVeridianService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianServiceMockRecorder
}

// MockVeridianServiceMockRecorder is the mock recorder for MockVeridianService.
type MockVeridianServiceMockRecorder struct {
	mock *MockVeridianService
}

// NewMockVeridianService creates a new mock instance.
func NewMockVeridianService(ctrl *gomock.Controller) *MockVeridianService {
	mock := &MockVeridianService{ctrl: ctrl}
	mock.recorder = &MockVeridianServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianService) EXPECT() *MockVeridianServiceMockRecorder {
	return m.recorder
}

// AttachMember mocks base method.
func (m *MockVeridianService) AttachMember(arg0 context.Context, arg1 domain.AttachMemberInput) (*domain.AttachMemberResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachMember", arg0, arg1)
	ret0, _ := ret[0].(*domain.AttachMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachMember indicates an expected call of AttachMember.
func (mr *MockVeridianServiceMockRecorder) AttachMember(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachMember", reflect.TypeOf((*MockVeridianService)(nil).AttachMember), arg0, arg1)
}

// AttachOwner mocks base method.
func (m *MockVeridianService) AttachOwner(arg0 context.Context, arg1 domain.AttachOwnerInput) (*domain.AttachOwnerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachOwner", arg0, arg1)
	ret0, _ := ret[0].(*domain.AttachOwnerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachOwner indicates an expected call of AttachOwner.
func (mr *MockVeridianServiceMockRecorder) AttachOwner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachOwner", reflect.TypeOf((*MockVeridianService)(nil).AttachOwner), arg0, arg1)
}

// GenerateMagicLink mocks base method.
func (m *MockVeridianService) GenerateMagicLink(arg0 context.Context, arg1, arg2 string) (*domain.MagicLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMagicLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.MagicLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMagicLink indicates an expected call of GenerateMagicLink.
func (mr *MockVeridianServiceMockRecorder) GenerateMagicLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMagicLink", reflect.TypeOf((*MockVeridianService)(nil).GenerateMagicLink), arg0, arg1, arg2)
}

// GetStatus mocks base method.
func (m *MockVeridianService) GetStatus(arg0 context.Context, arg1 string) (*domain.StatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", arg0, arg1)
	ret0, _ := ret[0].(*domain.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockVeridianServiceMockRecorder) GetStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockVeridianService)(nil).GetStatus), arg0, arg1)
}

// GetLimits mocks base method.
func (m *MockVeridianService) GetLimits(arg0 context.Context, arg1 string) (*domain.LimitsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits", arg0, arg1)
	ret0, _ := ret[0].(*domain.LimitsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockVeridianServiceMockRecorder) GetLimits(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockVeridianService)(nil).GetLimits), arg0, arg1)
}

// GrantUnlimited mocks base method.
func (m *MockVeridianService) GrantUnlimited(arg0 context.Context, arg1 domain.GrantUnlimitedInput) (*domain.GrantUnlimitedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantUnlimited", arg0, arg1)
	ret0, _ := ret[0].(*domain.GrantUnlimitedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantUnlimited indicates an expected call of GrantUnlimited.
func (mr *MockVeridianServiceMockRecorder) GrantUnlimited(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantUnlimited", reflect.TypeOf((*MockVeridianService)(nil).GrantUnlimited), arg0, arg1)
}

// Health mocks base method.
func (m *MockVeridianService) Health(arg0 context.Context, arg1 string) (*domain.TenantHealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", arg0, arg1)
	ret0, _ := ret[0].(*domain.TenantHealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockVeridianServiceMockRecorder) Health(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockVeridianService)(nil).Health), arg0, arg1)
}

// Provision mocks base method.
func (m *MockVeridianService) Provision(arg0 context.Context, arg1 domain.ProvisionInput) (*domain.ProvisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", arg0, arg1)
	ret0, _ := ret[0].(*domain.ProvisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provision indicates an expected call of Provision.
func (mr *MockVeridianServiceMockRecorder) Provision(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockVeridianService)(nil).Provision), arg0, arg1)
}

// Purge mocks base method.
func (m *MockVeridianService) Purge(arg0 context.Context, arg1 domain.PurgeInput) (*domain.PurgeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purge", arg0, arg1)
	ret0, _ := ret[0].(*domain.PurgeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Purge indicates an expected call of Purge.
func (mr *MockVeridianServiceMockRecorder) Purge(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockVeridianService)(nil).Purge), arg0, arg1)
}

// Restore mocks base method.
func (m *MockVeridianService) Restore(arg0 context.Context, arg1 domain.RestoreInput) (*domain.RestoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", arg0, arg1)
	ret0, _ := ret[0].(*domain.RestoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockVeridianServiceMockRecorder) Restore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockVeridianService)(nil).Restore), arg0, arg1)
}

// Resume mocks base method.
func (m *MockVeridianService) Resume(arg0 context.Context, arg1 domain.ResumeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockVeridianServiceMockRecorder) Resume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockVeridianService)(nil).Resume), arg0, arg1)
}

// SoftDelete mocks base method.
func (m *MockVeridianService) SoftDelete(arg0 context.Context, arg1 domain.SoftDeleteInput) (*domain.SoftDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", arg0, arg1)
	ret0, _ := ret[0].(*domain.SoftDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockVeridianServiceMockRecorder) SoftDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockVeridianService)(nil).SoftDelete), arg0, arg1)
}

// Suspend mocks base method.
func (m *MockVeridianService) Suspend(arg0 context.Context, arg1 domain.SuspendInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockVeridianServiceMockRecorder) Suspend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockVeridianService)(nil).Suspend), arg0, arg1)
}

// Touch mocks base method.
func (m *MockVeridianService) Touch(arg0 context.Context, arg1 string) (*domain.TouchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", arg0, arg1)
	ret0, _ := ret[0].(*domain.TouchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Touch indicates an expected call of Touch.
func (mr *MockVeridianServiceMockRecorder) Touch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockVeridianService)(nil).Touch), arg0, arg1)
}

// UpdatePlan mocks base method.
func (m *MockVeridianService) UpdatePlan(arg0 context.Context, arg1 domain.UpdatePlanInput) (*domain.UpdatePlanResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", arg0, arg1)
	ret0, _ := ret[0].(*domain.UpdatePlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlan indicates an expected call of UpdatePlan.
func (mr *MockVeridianServiceMockRecorder) UpdatePlan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockVeridianService)(nil).UpdatePlan), arg0, arg1)
}

// UsageSummary mocks base method.
func (m *MockVeridianService) UsageSummary(arg0 context.Context, arg1 string) (*domain.UsageSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsageSummary", arg0, arg1)
	ret0, _ := ret[0].(*domain.UsageSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsageSummary indicates an expected call of UsageSummary.
func (mr *MockVeridianServiceMockRecorder) UsageSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsageSummary", reflect.TypeOf((*MockVeridianService)(nil).UsageSummary), arg0, arg1)
}

// LookupByEmail mocks base method.
func (m *MockVeridianService) LookupByEmail(arg0 context.Context, arg1 string) (*domain.DiscoveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupByEmail", arg0, arg1)
	ret0, _ := ret[0].(*domain.DiscoveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupByEmail indicates an expected call of LookupByEmail.
func (mr *MockVeridianServiceMockRecorder) LookupByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupByEmail", reflect.TypeOf((*MockVeridianService)(nil).LookupByEmail), arg0, arg1)
}

// WipeTestTenants mocks base method.
func (m *MockVeridianService) WipeTestTenants(arg0 context.Context, arg1 domain.WipeTestTenantsInput) (*domain.WipeTestTenantsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WipeTestTenants", arg0, arg1)
	ret0, _ := ret[0].(*domain.WipeTestTenantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WipeTestTenants indicates an expected call of WipeTestTenants.
func (mr *MockVeridianServiceMockRecorder) WipeTestTenants(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WipeTestTenants", reflect.TypeOf((*MockVeridianService)(nil).WipeTestTenants), arg0, arg1)
}
