// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianAPIKeyGraceRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianAPIKeyGraceRepository is a mock of VeridianAPIKeyGraceRepository interface.
type MockVeridianAPIKeyGraceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianAPIKeyGraceRepositoryMockRecorder
}

// MockVeridianAPIKeyGraceRepositoryMockRecorder is the mock recorder for MockVeridianAPIKeyGraceRepository.
type MockVeridianAPIKeyGraceRepositoryMockRecorder struct {
	mock *MockVeridianAPIKeyGraceRepository
}

// NewMockVeridianAPIKeyGraceRepository creates a new mock instance.
func NewMockVeridianAPIKeyGraceRepository(ctrl *gomock.Controller) *MockVeridianAPIKeyGraceRepository {
	mock := &MockVeridianAPIKeyGraceRepository{ctrl: ctrl}
	mock.recorder = &MockVeridianAPIKeyGraceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianAPIKeyGraceRepository) EXPECT() *MockVeridianAPIKeyGraceRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockVeridianAPIKeyGraceRepository) DeleteByID(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockVeridianAPIKeyGraceRepositoryMockRecorder) DeleteByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockVeridianAPIKeyGraceRepository)(nil).DeleteByID), arg0, arg1)
}

// Insert mocks base method.
func (m *MockVeridianAPIKeyGraceRepository) Insert(arg0 context.Context, arg1 *domain.APIKeyGraceEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockVeridianAPIKeyGraceRepositoryMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockVeridianAPIKeyGraceRepository)(nil).Insert), arg0, arg1)
}

// ListExpired mocks base method.
func (m *MockVeridianAPIKeyGraceRepository) ListExpired(arg0 context.Context, arg1 time.Time) ([]*domain.APIKeyGraceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpired", arg0, arg1)
	ret0, _ := ret[0].([]*domain.APIKeyGraceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpired indicates an expected call of ListExpired.
func (mr *MockVeridianAPIKeyGraceRepositoryMockRecorder) ListExpired(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpired", reflect.TypeOf((*MockVeridianAPIKeyGraceRepository)(nil).ListExpired), arg0, arg1)
}
