// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: VeridianService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockVeridianService is a mock of VeridianService interface.
type MockVeridianService struct {
	ctrl     *gomock.Controller
	recorder *MockVeridianServiceMockRecorder
}

// MockVeridianServiceMockRecorder is the mock recorder for MockVeridianService.
type MockVeridianServiceMockRecorder struct {
	mock *MockVeridianService
}

// NewMockVeridianService creates a new mock instance.
func NewMockVeridianService(ctrl *gomock.Controller) *MockVeridianService {
	mock := &MockVeridianService{ctrl: ctrl}
	mock.recorder = &MockVeridianServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVeridianService) EXPECT() *MockVeridianServiceMockRecorder {
	return m.recorder
}

// GenerateMagicLink mocks base method.
func (m *MockVeridianService) GenerateMagicLink(arg0 context.Context, arg1, arg2 string) (*domain.MagicLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMagicLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.MagicLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMagicLink indicates an expected call of GenerateMagicLink.
func (mr *MockVeridianServiceMockRecorder) GenerateMagicLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMagicLink", reflect.TypeOf((*MockVeridianService)(nil).GenerateMagicLink), arg0, arg1, arg2)
}

// GetStatus mocks base method.
func (m *MockVeridianService) GetStatus(arg0 context.Context, arg1 string) (*domain.StatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", arg0, arg1)
	ret0, _ := ret[0].(*domain.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockVeridianServiceMockRecorder) GetStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockVeridianService)(nil).GetStatus), arg0, arg1)
}

// Provision mocks base method.
func (m *MockVeridianService) Provision(arg0 context.Context, arg1 domain.ProvisionInput) (*domain.ProvisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", arg0, arg1)
	ret0, _ := ret[0].(*domain.ProvisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provision indicates an expected call of Provision.
func (mr *MockVeridianServiceMockRecorder) Provision(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockVeridianService)(nil).Provision), arg0, arg1)
}

// Resume mocks base method.
func (m *MockVeridianService) Resume(arg0 context.Context, arg1 domain.ResumeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockVeridianServiceMockRecorder) Resume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockVeridianService)(nil).Resume), arg0, arg1)
}

// SoftDelete mocks base method.
func (m *MockVeridianService) SoftDelete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockVeridianServiceMockRecorder) SoftDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockVeridianService)(nil).SoftDelete), arg0, arg1)
}

// Suspend mocks base method.
func (m *MockVeridianService) Suspend(arg0 context.Context, arg1 domain.SuspendInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockVeridianServiceMockRecorder) Suspend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockVeridianService)(nil).Suspend), arg0, arg1)
}

// UpdatePlan mocks base method.
func (m *MockVeridianService) UpdatePlan(arg0 context.Context, arg1 domain.UpdatePlanInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlan indicates an expected call of UpdatePlan.
func (mr *MockVeridianServiceMockRecorder) UpdatePlan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockVeridianService)(nil).UpdatePlan), arg0, arg1)
}

// WipeTestTenants mocks base method.
func (m *MockVeridianService) WipeTestTenants(arg0 context.Context, arg1 domain.WipeTestTenantsInput) (*domain.WipeTestTenantsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WipeTestTenants", arg0, arg1)
	ret0, _ := ret[0].(*domain.WipeTestTenantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WipeTestTenants indicates an expected call of WipeTestTenants.
func (mr *MockVeridianServiceMockRecorder) WipeTestTenants(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WipeTestTenants", reflect.TypeOf((*MockVeridianService)(nil).WipeTestTenants), arg0, arg1)
}
